version: '3'
services:
  mysql_orm:
    image: mysql/mysql-server:5.7
    volumes:
      - orm_data_mysql:/var/lib/mysql
    ports:
      - ${LOCAL_IP}:${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  mysql8_orm:
    image: mysql/mysql-server:8.0
    volumes:
      - orm_data_mysql8:/var/lib/mysql
    ports:
      - ${LOCAL_IP}:${MYSQL8_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  redis_orm:
    image: redislabs/redisearch:2.0.15
    ports:
      - ${LOCAL_IP}:${REDIS_PORT}:6379
  redis_orm_22:
    image: redislabs/redisearch:2.2.10
    ports:
      - ${LOCAL_IP}:${REDIS_PORT_22}:6379
volumes:
  orm_data_mysql: {}
  orm_data_mysql8: {}
